server:
  port: 9991
  shutdown: graceful
spring:
  application:
    name: pagamentos
  profiles:
    active: dev

  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 1


rest-template:
  readTimeout: 10000
  connectionTimeout: 10000
  password: 112023
  protocol: TLS
  maxRetry: 10
  retryInterval: 5
  keyStoreInstance: PKCS12
  classPath: classpath:COPPETEC2024.pfx

management:
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
      show-details: always
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: 'prometheus'
      base-path: /actuator
      cors:
        allowed-origins: "*"
    enabled-by-default: false


logging:
  file:
    name: logs/coppetec-bb.log

feign:
  client:
    default:
      config:
        numberRetry: 3
        retryInterval: 5