enable:
  schedule: ${ENABLE_SCHEDULE_PAYMENT}

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER_PAYMENT}
    password: ${DATASOURCE_PASSWORD_PAYMENT}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
        show_sql: false
        format_sql: false

bb:
  ambiente: gw-dev-app-key
  autenticacaoExtrato:
    autorizacao: ${BB_AUTH_SLIP_AUTHORIZATION}
    chaveAplicacao: ${BB_AUTH_SLIP_APPLICATION_KEY}
  autenticacaoTransferencia:
    autorizacao: ${BB_AUTH_TRANSFER_AUTHORIZATION}
    chaveAplicacao: ${BB_AUTH_TRANSFER_APPLICATION_KEY}
  endpoints:
    baseUrl: https://api-ip.bb.com.br
    autenticar: https://oauth.bb.com.br/oauth/token
    buscarSolicitacao: https://api-ip.bb.com.br/pagamentos-lote/v1/{id}/solicitacao
    buscarTransferencia: https://api-ip.bb.com.br/pagamentos-lote/v1/transferencias/{id}
    consultar: https://api-ip.bb.com.br/pagamentos-lote/v1/lotes-transferencias
    transferir: https://api-ip.bb.com.br/pagamentos-lote/v1/lotes-transferencias
    lotesTransferencias: https://api-ip.bb.com.br/pagamentos-lote/v1/lotes-transferencias
    liberarLote: https://api-ip.bb.com.br/pagamentos-lote/v1/liberar-pagamentos
    extrato: https://api-extratos.bb.com.br

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

services:
  log:
    url: LOG-DEV